pd_music/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
  get "login", to: "login#index"
  post "login/authenicate", to: "login#authenicate"
  get "login/signup", to: "login#signup"
  post "login/register", to: "login#register"
  get "login/logout", to: "login#logout"
  get "login/forgot_password", to: "login#forgot_password"
  post "login/reset_password", to: "login#reset_password"
  get "login/reset", to: "login#new_password"
  post "login/change_password", to: "login#change_password"

  post "dashboard/filter", to: "dashboard#filter_report"
  get "dashboard/datatable", to: "dashboard#dashboard_datatable"
  post "dashboard/change_tab", to: "dashboard#change_tab"
  post "dashboard/comment", to: "dashboard#add_comment"
  post "dashboard/view_user_comment", to: "dashboard#view_user_comment"
  post "dashboard/update_status", to: "dashboard#update_status"
  post "dashboard/add_exam_date", to: "dashboard#add_exam_date"

  get "report", to: "report#index"
  get "report/filter_user_or_subject", to: "report#filter_user_or_subject"
  get "report/filter_category", to: "report#filter_category"
  get "report/filter_homework", to: "report#filter_homework"
  get "report/filter_graph", to: "report#filter_graph"

  resources :homework
  post "homework/do/create_question", to: "homework#create_question"
  get "homework/do/detail_datatable", to: "homework#detail_datatable"
  get "homework/do/detail_score_datatable", to: "homework#get_detail_score"
  get "homework/do/datatable", to: "homework#datatable"
  get "homework/do/homework", to: "homework#do_homework"
  post "homework/do/set_audio", to: "homework#set_audio"
  post "homework/do/update_status", to: "homework#update_status"
  get "homework/do/reveal_answer", to: "homework#get_reveal_answer"
  post "homework/do/next_question", to: "homework#get_next_question"
  get "homework/do/review_homework", to: "homework#review_homework"
  post "homework/do/give_homework_score", to: "homework#give_score"
  post "homework/do/reject_homework", to: "homework#reject_homework"
  get "homework/subject/list", to: "homework#subject_list" 
  post "homework/create_tag", to: "homework#create_tag"
  get "homework/show/get_improvement_detail", to: "homework#get_improvement"
  post "homework/add_improvement", to: "homework#add_improvement"
  get "homework/show/homework_table", to: "homework#show_homework_table"
  delete "homework/show/delete_homework", to: "homework#delete_homework"
  post "homework/add_type", to: "homework#add_homework_type"
  post "homework/answer_format", to: "homework#select_answer_format"
  post "homework/add/question", to: "homework#add_questions"
  post "homework/add_choice", to: "homework#add_choices"
  get "homework/subject/get_user", to: "homework#get_user_homework_mapping"
  post "homework/add_user", to: "homework#add_user_to_homework"

  resources :participation
  post "participation/filter_report", to: "participation#filter"
  post "participation/add_subject", to: "participation#add_subject"
  post "participation/add_event", to: "participation#add_event"
  post "participation/add_user", to: "participation#add_user_to_subject"
  get "participation/subject/get_user", to: "participation#get_participate_of_user"
  post "participation/filter_subject", to: "participation#search_subject"

  resources :user
  get "user/datatable", to: "user#datatable"
  post "user/upload_profile_picture", to: "user#upload_profile_picture"
  post "user/list/approved", to: "user#approve_user"

  get "settings/notification", to: "notification#index"
  post "settings/save_notification", to: "notification#save_notification_setting"
  post "notification/filter", to: "notification#filter"
  post "notification/update", to: "notification#update_noti"
  
  get "settings/permission", to: "permission#index"
  post "settings/update_permission", to: "permission#update_permission"

  get "food", to: "food#index"
  post "food/set_order_rule", to: "food#setting_order"
  post "food/export_order", to: "food#export_order"
  get "food/filter_date", to: "food#filter_date"
  post "food/add_coupon", to: "food#add_coupon"
  get "food/restaurants", to: "food#restaurant"
  delete "food/restaurants", to: "food#destroy"
  post "food/restaurants/update_status", to: "food#update_restaurant_status"
  post "food/create", to: "food#create"
  get "food/menu", to: "food#menu_list"
  get "food/menu/datatable", to: "food#menu_datatable"
  post "food/menu/create", to: "food#create_menu"
  post "food/menu/option_create", to: "food#create_option"
  get "food/menu/get_option", to: "food#get_option"
  get "food/menu/get_menu", to: "food#get_menu"
  post "food/menu/update_status", to: "food#update_status"
  get "food/order", to: "food#order"
  delete "food/order", to: "food#destroy_order"
  get "food/order/get_menu", to: "food#get_menu_order"
  post "food/order/confirm", to: "food#confirm_order"
  get "food/order/change_date", to: "food#change_date"

  get "contact_us", to: "contact_us#index"

  get "activity_log", to: "activity_log#index"
  get "activity_log/datatable", to: "activity_log#datatable"

  get "category/show/datatable", to: "category#datatable"
  resources :category

  get "homework_type/show/datatable", to: "homework_type#datatable"
  resources :homework_type
end

pd_music/app/models/participation.rb
class Participation < ApplicationRecord
end

pd_music/app/helpers/participation_helper.rb
module ParticipationHelper
    require "json"

    def summary_data participate
        data = Hash.new
        data["rows"] = []
        participate.each do |pt|
            count_participation = 0
            count_late = 0
            count_not_participation = 0
            person = []
            unless pt.participation.blank?
                json = JSON.parse(pt.participation)
                json.each do |k, v|
                    count_participation += v["participate"]
                    count_late += v["late"]
                    count_not_participation += v["not_participate"]
                end
            end
            person << "#{pt.firstname} #{pt.lastname}"
            person << get_image(pt.profile_pic, pt.firstname, pt.lastname, "subject", count_participation, count_late, count_not_participation)
            person << count_participation
            person << count_late
            person << count_not_participation
            data["rows"] << person
        end

        data.to_json
    end

    def get_image picture, firstname, lastname, type, participate, late, not_participate
        picture_path = picture.attached? ? url_for(picture) : "#{APP_CONFIG[:application_path]}/pictures/no_image.jpg"
        txt_participate = type == "event" ? "เข้าร่วม" : "มา"
        txt_not_particapate = type == "event" ? "ไม่เข้าร่วม" : "ไม่มา"
        tooltip = "<div style=\"padding:15px;\">" +
            "<img src=\"#{picture_path}\" class=\"border rounded-circle mb-3\" style=\"width:100px; height:100px\"><br/>" +
            "<p>#{firstname} #{lastname}</p>" +
            "<table class=\"information\">" +
            participate_icon(participate, txt_participate) +
            late_icon(late) +
            not_participate_icon(not_participate, txt_not_particapate) +
            "</table>" + "</div>"
        tooltip
    end

    def participate_icon participate, text
        participation = "<tr>" +
            "<td><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-person-check-fill tooltip-participate me-2\" viewBox=\"0 0 16 16\">"+
            "<path fill-rule=\"evenodd\" d=\"M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0\"/>"+
            "<path d=\"M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6\"/>"+
            "</svg>#{text}</td>" +
            "<td><span class=\"tooltip-participate ps-2\"><b>#{participate}</b></span></td>" + "</tr>"
        return participation
    end

    def late_icon late
        if late.blank?
            return ""
        else
            lated = "<tr>" +
                "<td><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-person-dash-fill tooltip-late me-2\" viewBox=\"0 0 16 16\">"+
                "<path fill-rule=\"evenodd\" d=\"M11 7.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5\"/>"+
                "<path d=\"M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6\"/>"+
                "</svg>มาสาย</td>" +
                "<td><span class=\"tooltip-late ps-2\"><b>#{late}</b></span></td>" + "</tr>"
            return lated
        end
    end

    def not_participate_icon not_participate, text
        not_participation = "<tr>" +
            "<td><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-person-x-fill tooltip-not-participate me-2\" viewBox=\"0 0 16 16\">"+
            "<path fill-rule=\"evenodd\" d=\"M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m6.146-2.854a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708\"/>"+
            "</svg>#{text}</td>" +
            "<td><span class=\"tooltip-not-participate ps-2\"><b>#{not_participate}</b></span></td>" + "</tr>"
        return not_participation
    end

    def summary_concert participate
        data = Hash.new
        data["rows"] = []
        
        participate.each do |pt|
            count_participation = 0
            count_not_participation = 0
            event = []
            unless pt.participation.blank?
                json = JSON.parse(pt.participation)
                json.each do |k, v|
                    count_participation += v["participate"]
                    count_not_participation += v["not_participate"]
                end
            end
            event << "#{pt.firstname} #{pt.lastname}"
            event << get_image(pt.profile_pic, pt.firstname, pt.lastname, "event", count_participation, "", count_not_participation)
            event << count_participation
            event << count_not_participation
            data["rows"] << event
        end

        data.to_json
    end

    def get_check_permission type
        arr_permission = case type
                         when "event" then [18, 21, 22]
                         else [18, 21, 22]
                         end
        return arr_permission
    end

    def get_add_user_permission type
        arr_permission = case type
                         when "event" then [20, 21]
                         else [20, 21]
                         end
        return arr_permission
    end

    def checked_participate json, date
        participate = false
        if json.present?
            json_data = json.instance_of?(String) ? JSON.parse(json) : json
            participate = true if json_data.dig(date, "participate").to_i > 0
        end 
        participate
    end

    def checked_late json, date
        participate = false
        if json.present?
            json_data = json.instance_of?(String) ? JSON.parse(json) : json
            participate = true if json_data.dig(date, "late").to_i > 0
        end 
        participate
    end

    def checked_not_participate json, date
        participate = true
        # if json.present?
        #     json_data = json.instance_of?(String) ? JSON.parse(json) : json
        #     participate = true if json_data.dig(date, "not_participate").to_i > 0
        # end 
        if checked_participate(json, date) || checked_late(json, date)
            participate = false
        end
        participate
    end

    def get_display_class classname, room
        if classname.include?("มัธยมศึกษา")
            c, m = classname.split(" "); 
            text = "ม.#{m} ห้อง #{room}"
        else
            text = "#{classname} ห้อง #{room}"
        end
        text
    end
    
    def study_class
        arr_class = []
        arr_class << ["ประถมศึกษาปีที่ 1", "ประถมศึกษาปีที่ 2", "ประถมศึกษาปีที่ 3", "ประถมศึกษาปีที่ 4", "ประถมศึกษาปีที่ 5", "ประถมศึกษาปีที่ 6"]
        arr_class << ["EP 1", "EP 2", "EP 3", "EP 4", "EP 5", "EP 6"]
        arr_class << ["CEP 1", "CEP 2", "CEP 3", "CEP 4", "CEP 5", "CEP 6"]
        arr_class << "อื่นๆ"
        arr_class.flatten
    end

    def room
        number = (1..20).to_a
    end

    def study_class_and_room
        arr_class_and_room = []
        arr_class = study_class()
        arr_room = room()
        arr_class.each do |c|
            next if c == "อื่นๆ"
            arr_room.each {|r| arr_class_and_room << ["#{c}/#{r}", "#{c}_#{r}"]}
        end
        arr_class_and_room
    end
end

pd_music/app/views/participation/_add_event.html.erb
<div class="div-add-subject-parti position-absolute bottom-0 end-0 me-3 mb-3">
    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-plus-circle-fill icon" viewBox="0 0 16 16" data-bs-toggle="modal" data-bs-target="#createEventParticipation">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z"/>
    </svg>
</div>

<div class="modal fade" id="createEventParticipation" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="createEventParticipationLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <%= form_for :form_create_event, url: participation_add_event_path(format: :json), method: :POST, data: { action: "submit->participation#createEvent" } do |f| %>
            <div class="modal-header">
                <h5 class="modal-title" id="createEventParticipationLabel">Create event</h5>
                <button type="button" class="btn-close" id="close-icon-create-event-dialog" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="event_name" class="form-label">Event name :</label>
                    <%= f.text_field :event, value: params[:event], class: "form-control", id: "event_name" %>
                </div>

                <div class="mb-4">
                    <label for="description" class="form-label">Description <i>-(optional)</i> :</label>
                    <%= f.text_field :description, value: params[:description], class: "form-control", id: "event_description" %>
                </div>

                <div class="mb-3 row">
                    <label for="event_date" class="col-sm-1 col-form-label">Date: </label>
                    <div class="col-sm-11">
                        <%= f.date_field :event_date, as: :date, value: params[:event_date], class: "form-control" , id: "event_date" %>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <%= f.submit "Create", class: "btn btn-primary w-25" %>
                <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">Close</button>
            </div>
            <% end %>
        </div>
    </div>
</div>

pd_music/app/views/participation/_add_subject.html.erb
<div class="div-add-subject-parti position-absolute bottom-0 end-0 me-3 mb-3">
    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-plus-circle-fill icon" viewBox="0 0 16 16" data-bs-toggle="modal" data-bs-target="#createSubjectParticipation">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z"/>
    </svg>
</div>

<div class="modal fade" id="createSubjectParticipation" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="createSubjectParticipationLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <%= form_for :form_create_subject, url: participation_add_subject_path(format: :json), method: :POST, data: { action: "submit->participation#createSubject" } do |f| %>
            <div class="modal-header">
                <h5 class="modal-title" id="createSubjectParticipationLabel">Create subject</h5>
                <button type="button" class="btn-close" id="close-icon-create-subject-dialog" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="txt_subject" class="form-label">Subject :</label>
                    <%= f.text_field :subject, value: params[:subject], class: "form-control", id: "txt_subject" %>
                </div>

                <div class="mb-4">
                    <label for="description" class="form-label">Description <i>-(optional)</i> :</label>
                    <%= f.text_field :description, value: params[:description], class: "form-control", id: "description" %>
                </div>

                <div class="mb-3 row">
                    <label for="class_period" class="col-sm-3 col-form-label">Class period: </label>
                    <div class="col-sm-9">
                        <%= f.text_field :class_period, value: params[:class_period], class: "form-control w-50", id: "class_period" %>
                    </div>
                </div>

                <%= f.hidden_field :subject_type, value: "participation" %>
                
            </div>
            <div class="modal-footer">
                <%= f.submit "Create", class: "btn btn-primary w-25" %>
                <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">Close</button>
            </div>
            <% end %>
        </div>
    </div>
</div>

pd_music/app/views/participation/_subject_list.html.erb
<% if data.present? %>
    <% data.each do |sj| %>
        <div class="col">
            <div class="card mb-3 me-3">
                <% id = type == "subject" ? sj.subject_id : sj.event_id %>
                <% name = type == "subject" ? sj.subject_name : sj.event_name %>
                <div class="delete-subject position-absolute end-0 pe-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill text-white icon delete" viewBox="0 0 16 16" data-bs-toggle="modal" data-bs-target="#deleteSubjectModal" data-action="click->participation#setDeleteId" data-participation-subject-id-param="<%= id %>" data-participation-name-param="<%= name %>" data-participation-type-param="<%= type %>">
                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                    </svg>
                </div>
                <% rand_img = rand(1..5) %>
                <img src="<%= APP_CONFIG[:application_path] %>/pictures/banners/music_banner_<%= rand_img %>.png" class="card-img-top">
                <div class="card-body div-card-body-parti">
                    <div class="user-created-profile">
                        <%= image_tag(sj.profile_pic.attached? ? url_for(sj.profile_pic) : "#{APP_CONFIG[:application_path]}/pictures/no_image.jpg", class: "img-profile-subject-parti rounded-circle position-absolute end-0 me-3", width: "100px", height: "100px") %>
                    </div>
                    <h5 class="card-title"><%= name %></h5>
                    <p class="card-text"><%= sj.description %></p>
                    <% date = type == "subject" ? sj.created_at : sj.event_date %>
                    <p class="card-text position-absolute bottom-0"><small class="text-muted"><%= date.strftime("%d/%m/%Y") %></small></p>
                    <p class="float-end position-absolute bottom-0 end-0">
                        <% if can_view_menu?(permission) %>
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person-plus-fill icon mx-2" viewBox="0 0 16 16" data-bs-toggle="modal" data-bs-target="#addUserToSubject" data-action="click->participation#openAddUserModal" data-participation-subject-id-param="<%= id %>" data-participation-type-param="<%= type %>" data-participation-url-param="<%= participation_subject_get_user_path() %>">
                                <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                                <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"/>
                            </svg>
                        <% end %>
                        <% if can_view_menu?(permission) %>
                            <%= link_to edit_participation_path(id: id, type: type) do %>
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-ui-checks icon mx-2" viewBox="0 0 16 16">
                                <path d="M7 2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5zM2 1a2 2 0 0 0-2 2v2a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2zm0 8a2 2 0 0 0-2 2v2a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2v-2a2 2 0 0 0-2-2zm.854-3.646a.5.5 0 0 1-.708 0l-1-1a.5.5 0 1 1 .708-.708l.646.647 1.646-1.647a.5.5 0 1 1 .708.708zm0 8a.5.5 0 0 1-.708 0l-1-1a.5.5 0 0 1 .708-.708l.646.647 1.646-1.647a.5.5 0 0 1 .708.708zM7 10.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5zm0-5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m0 8a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5"/>
                            </svg>
                            <% end %>
                        <% end %>
                    </p>
                </div>
            </div>
        </div>
    <% end %>
<% else %>
    <div class="no-subject-image h-100 m-auto text-center" style="align-content: center;">
        <%= image_tag("#{APP_CONFIG[:application_path]}/pictures/no-subject.png", width: "200px", height: "200px") %>
        <p>No subject, Please add the subject</p>
    </div>
<% end %>

pd_music/app/views/participation/edit.html.erb
<div class="mb-3 h-100" data-controller="participation">
    <% today = DateTime.now().strftime("%d/%m/%Y") %>
    <%= form_for :form_paritipation, url: participation_path(format: :json, date: today, type: params["type"]), class: "h-90", method: :PATCH do |f|%>
    <div class="row g-3 p-3 border-bottom">
        <% name = params["type"] == "event" ? @subject.event_name : @subject.subject_name %>
        <div class="col"><h5><%= params["type"].capitalize %>: <%= name %></h5></div>
        <div class="col text-center"><span>Date: <%= today %></span></div>
        <div class="col text-end">
            <% if @participation.present? %>
                <% if can_view_menu?(get_check_permission(params["type"])) %>
                    <%= f.submit "Save", class: "btn btn-primary w-25 me-5" %>
                <% end %>
            <% else %>
                <% if can_view_menu?(get_add_user_permission(params["type"])) %>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addUserToSubject" data-action="click->participation#openAddUserModal" data-participation-subject-id-param="<%= @subject.id %>" data-participation-page-param="edit" data-participation-type-param="<%= params["type"] %>" data-participation-url-param="<%= participation_subject_get_user_path() %>">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                        <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                        <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"/>
                    </svg> Add student
                </button>
                <% end %>
            <% end %>
        </div>
    </div>
    <% if @participation.present? %>
    <div class="table-check-name w-75 m-auto mt-5">
        <table class="table table-hover table-check-list">
            <thead>
                <tr>
                    <th class="column-0"></th>
                    <th class="column-1">Name</th>
                    <th class="column-2">Class/Room</th>
                    <% if params["type"] == "event" %>
                        <th class="column-3 event text-center">เข้าร่วม</th>
                        <th class="column-4 event text-center">ไม่เข้าร่วม</th>
                    <% else %>
                        <th class="column-3 text-center">มา</th>
                        <th class="column-4 text-center">มาสาย</th>
                        <th class="column-5 text-center">ไม่มา</th>
                    <% end %>
                </tr>
            </thead>
            <tbody>
                <% arr_id = [] %>
                <% @participation.each do |pt| %>
                <tr>
                    <td><%= image_tag(pt.profile_pic.attached? ? url_for(pt.profile_pic) : "#{APP_CONFIG[:application_path]}/pictures/no_image.jpg", class: "rounded-circle", width: "75px", height: "75px")  %></td>
                    <td class="truncate"><%= pt.firstname %> <%= pt.lastname %></td>
                    <td><%= pt.study_class %>/<%= pt.room %></td>
                    <% if params["type"] == "event" %>
                        <td class="text-center"><%= f.radio_button "participate_#{pt.participate_id}", 1, checked: checked_participate(pt.participation, today), class: "form-check-input", id: "participate-#{pt.user_id}" %></td>
                        <td class="text-center"><%= f.radio_button "participate_#{pt.participate_id}", 3, checked: checked_not_participate(pt.participation, today), class: "form-check-input", id: "no_participate-#{pt.user_id}" %></td>
                    <% else %>
                        <td class="text-center"><%= f.radio_button "participate_#{pt.participate_id}", 1, checked: checked_participate(pt.participation, today), class: "form-check-input", id: "participate-#{pt.user_id}" %></td>
                        <td class="text-center"><%= f.radio_button "participate_#{pt.participate_id}", 2, checked: checked_late(pt.participation, today), class: "form-check-input", id: "late-#{pt.user_id}" %></td>
                        <td class="text-center"><%= f.radio_button "participate_#{pt.participate_id}", 3, checked: checked_not_participate(pt.participation, today), class: "form-check-input", id: "no_participate-#{pt.user_id}" %></td>
                    <% end %>
                    <% arr_id << pt.participate_id %>
                </tr>
                <% end %>
               <%= f.hidden_field :arr_id, value: arr_id.join(",") %>
            </tbody>
        </table>
    </div>
    <% else %>
        <div class="no-subject-image h-100 m-auto text-center" style="align-content: center;">
            <%= image_tag("#{APP_CONFIG[:application_path]}/pictures/no-subject.png", width: "200px", height: "200px") %>
            <p>No student in this subject, Please add the student</p>
        </div>

        <% @user = User.where(status: "active", role: 3) %>
        <div class="div-add-user-modal">
            <%= render partial: "add_user_to_subject", locals: { href: edit_participation_path(id: @subject.id, type: params["type"]) } %>
        </div>
    <% end %>
    <% end %>
</div>