pd_music/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
  get "login", to: "login#index"
  post "login/authenicate", to: "login#authenicate"
  get "login/signup", to: "login#signup"
  post "login/register", to: "login#register"
  get "login/logout", to: "login#logout"
  get "login/forgot_password", to: "login#forgot_password"
  post "login/reset_password", to: "login#reset_password"
  get "login/reset", to: "login#new_password"
  post "login/change_password", to: "login#change_password"

  post "dashboard/filter", to: "dashboard#filter_report"
  get "dashboard/datatable", to: "dashboard#dashboard_datatable"
  post "dashboard/change_tab", to: "dashboard#change_tab"
  post "dashboard/comment", to: "dashboard#add_comment"
  post "dashboard/view_user_comment", to: "dashboard#view_user_comment"
  post "dashboard/update_status", to: "dashboard#update_status"
  post "dashboard/add_exam_date", to: "dashboard#add_exam_date"

  get "report", to: "report#index"
  get "report/filter_user_or_subject", to: "report#filter_user_or_subject"
  get "report/filter_category", to: "report#filter_category"
  get "report/filter_homework", to: "report#filter_homework"
  get "report/filter_graph", to: "report#filter_graph"

  resources :homework
  post "homework/do/create_question", to: "homework#create_question"
  get "homework/do/detail_datatable", to: "homework#detail_datatable"
  get "homework/do/detail_score_datatable", to: "homework#get_detail_score"
  get "homework/do/datatable", to: "homework#datatable"
  get "homework/do/homework", to: "homework#do_homework"
  post "homework/do/set_audio", to: "homework#set_audio"
  post "homework/do/update_status", to: "homework#update_status"
  get "homework/do/reveal_answer", to: "homework#get_reveal_answer"
  post "homework/do/next_question", to: "homework#get_next_question"
  get "homework/do/review_homework", to: "homework#review_homework"
  post "homework/do/give_homework_score", to: "homework#give_score"
  post "homework/do/reject_homework", to: "homework#reject_homework"
  get "homework/subject/list", to: "homework#subject_list" 
  post "homework/create_tag", to: "homework#create_tag"
  get "homework/show/get_improvement_detail", to: "homework#get_improvement"
  post "homework/add_improvement", to: "homework#add_improvement"
  get "homework/show/homework_table", to: "homework#show_homework_table"
  delete "homework/show/delete_homework", to: "homework#delete_homework"
  post "homework/add_type", to: "homework#add_homework_type"
  post "homework/answer_format", to: "homework#select_answer_format"
  post "homework/add/question", to: "homework#add_questions"
  post "homework/add_choice", to: "homework#add_choices"
  get "homework/subject/get_user", to: "homework#get_user_homework_mapping"
  post "homework/add_user", to: "homework#add_user_to_homework"

  resources :participation
  post "participation/filter_report", to: "participation#filter"
  post "participation/add_subject", to: "participation#add_subject"
  post "participation/add_event", to: "participation#add_event"
  post "participation/add_user", to: "participation#add_user_to_subject"
  get "participation/subject/get_user", to: "participation#get_participate_of_user"
  post "participation/filter_subject", to: "participation#search_subject"

  resources :user
  get "user/datatable", to: "user#datatable"
  post "user/upload_profile_picture", to: "user#upload_profile_picture"
  post "user/list/approved", to: "user#approve_user"

  get "settings/notification", to: "notification#index"
  post "settings/save_notification", to: "notification#save_notification_setting"
  post "notification/filter", to: "notification#filter"
  post "notification/update", to: "notification#update_noti"
  
  get "settings/permission", to: "permission#index"
  post "settings/update_permission", to: "permission#update_permission"

  get "food", to: "food#index"
  post "food/set_order_rule", to: "food#setting_order"
  post "food/export_order", to: "food#export_order"
  get "food/filter_date", to: "food#filter_date"
  post "food/add_coupon", to: "food#add_coupon"
  get "food/restaurants", to: "food#restaurant"
  delete "food/restaurants", to: "food#destroy"
  post "food/restaurants/update_status", to: "food#update_restaurant_status"
  post "food/create", to: "food#create"
  get "food/menu", to: "food#menu_list"
  get "food/menu/datatable", to: "food#menu_datatable"
  post "food/menu/create", to: "food#create_menu"
  post "food/menu/option_create", to: "food#create_option"
  get "food/menu/get_option", to: "food#get_option"
  get "food/menu/get_menu", to: "food#get_menu"
  post "food/menu/update_status", to: "food#update_status"
  get "food/order", to: "food#order"
  delete "food/order", to: "food#destroy_order"
  get "food/order/get_menu", to: "food#get_menu_order"
  post "food/order/confirm", to: "food#confirm_order"
  get "food/order/change_date", to: "food#change_date"

  get "contact_us", to: "contact_us#index"

  get "activity_log", to: "activity_log#index"
  get "activity_log/datatable", to: "activity_log#datatable"

  get "category/show/datatable", to: "category#datatable"
  resources :category

  get "homework_type/show/datatable", to: "homework_type#datatable"
  resources :homework_type
end

pd_music/app/helpers/dashboard_helper.rb
module DashboardHelper
    def get_all_done data, num_category
        count = 0
        for i in 1..num_category
            count += data["category_#{i}"]["done"].to_i if data["category_#{i}"].present?
        end
        return count
    end

    def get_all_remain data, num_category
        count = 0
        for i in 1..num_category
            count += data["category_#{i}"]["remain"].to_i if data["category_#{i}"].present?
        end
        return count
    end

    def percent_done data, num_category
        total_done = get_all_done(data, num_category)
        total_remain = get_all_remain(data, num_category)
        total_task = total_done + total_remain
        return total_task == 0 ? 0 : (( (total_done.to_f/total_task.to_f).round(2) ) * 100).round
    end

    def get_done_task data, category_id
        return data["category_#{category_id}"].present? ? data["category_#{category_id}"]["done"].to_i : 0
    end

    def get_remain_task data, category_id
        return data["category_#{category_id}"].present? ? data["category_#{category_id}"]["remain"].to_i : 0
    end

    def percent_done_each_category data, category_id
        total_done = get_done_task(data, category_id)
        total_remain = get_remain_task(data, category_id)
        total_task = total_done + total_remain
        return total_task == 0 ? 0 : (( (total_done.to_f/total_task.to_f).round(2) ) * 100).round
    end

    def get_all_overdue data, num_category
        count = 0
        for i in 1..num_category
            count += data["category_#{i}"]["estimated"].to_i if data["category_#{i}"].present?
        end
        return count
    end

    def get_overdue_day data, num_category
        count = 0
        for i in 1..num_category
            count += data["category_#{i}"]["day"].to_i if data["category_#{i}"].present?
        end
        return count
    end

    def get_overdue_week data, num_category
        count = 0
        for i in 1..num_category
            count += data["category_#{i}"]["week"].to_i if data["category_#{i}"].present?
        end
        return count
    end

    def get_overdue_day_each_cat data
        return data["specific_category"]["day"].present? ? data["specific_category"]["day"].to_i : 0
    end

    def get_overdue_week_each_cat data
        return data["specific_category"]["week"].present? ? data["specific_category"]["week"].to_i : 0
    end

    def get_score_data data, category
        result = []
        category.each do |k, v|
            total_done = get_done_task(data, k)
            total_remain = get_remain_task(data, k)
            total_task = total_done + total_remain
            score = data["category_#{k}"].present? ? (data["category_#{k}"]["score"].to_f/total_task.to_f).round(2) : 0
            result << [v["name_en"], score]
        end
        return result
    end

    def can_access_action?
        return redirect_to path_to_root unless session["permission_roles"].include?(1)
    end

    def exam_date
        ["1 Day", "2 Day", "3 Day", "4 Day", "5 Day", "6 Day", "1 Week", "2 Week", "3 Week", "1 Month", "More than 1 month"]
    end

    def study_class
        ["ประถมศึกษา", "มัธยมศึกษาปีที่ 1", "มัธยมศึกษาปีที่ 2", "มัธยมศึกษาปีที่ 3", "มัธยมศึกษาปีที่ 4", "มัธยมศึกษาปีที่ 5", "มัธยมศึกษาปีที่ 6", "ปริญญาตรี", "มากกว่าปริญาตรี", "อื่นๆ"]
    end
end

pd_music/app/views/dashboard/_comment_dialog.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary me-1 float-end px-2 py-1" data-bs-toggle="modal" data-bs-target="#commentClassRoom">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
    </svg>
</button>

<!-- Modal -->
<div class="modal fade" id="commentClassRoom" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="commentClassRoomLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="commentClassRoomLabel">Comment behaviour</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <%= form_for :form_comment, url: dashboard_comment_path(format: :json), method: :POST do |f| %>
                <div class="mb-3 row">
                    <label for="comment-to" class="col-sm-2 col-form-label">To: </label>
                    <div class="col-sm-10">
                        <%= f.select :comment_to, @data["specific_category"]["student_list"], {}, class: "form-select", id: "comment-to" %>
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="subject" class="col-sm-2 col-form-label">Subject: </label>
                    <div class="col-sm-10">
                        <%= f.text_field :subject, value: "", class: "form-control", id: "subject" %>
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="comment" class="col-sm-2 col-form-label">Comment: </label>
                    <div class="col-sm-10">
                        <%= f.text_area :comment, value: "", class: "form-control", id: "comment", rows: "2" %>
                    </div>
                </div>

                <div class="mb-5 row">
                    <label for="comment" class="col-sm-2 col-form-label">Rating: </label>
                    <div class="col-sm-10 py-2">
                        <div class="stars">
                            <% for i in 0..4 do %>
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16" data-action="click->dashboard#rating" data-dashboard-rating-param="<%= i %>">
                                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                            </svg>
                            <% end %>
                        </div>
                        <%= f.hidden_field :rating, value: 0, id: "hide-rating"%>
                    </div>
                </div>

                <div class="mb-3 row text-center">
                    <%= f.submit "Comment", class: "btn btn-primary w-25 m-auto" %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

pd_music/app/views/dashboard/_filter_for_teacher.html.erb
<div class="filter-select-by form-check form-check-inline ms-5 my-3">
  <input class="form-check-input" type="radio" name="filter-by" id="individual" data-action="change->dashboard#filterName" data-dashboard-filter-by-param="individual">
  <label class="form-check-label ms-2" for="individual">
    Individual
  </label>
</div>
<div class="filter-select-by form-check form-check-inline ms-3">
  <input class="form-check-input" type="radio" name="filter-by" id="group" data-action="change->dashboard#filterName" data-dashboard-filter-by-param="group" checked>
  <label class="form-check-label ms-2" for="group">
    Group
  </label>
</div>

<div class="filter-box filter-select-by mb-3 ms-5">
    <%= form_for :form_date_filter, url: dashboard_change_tab_path(format: :json), method: :POST, html: { data: { "action": "submit->dashboard#filterNameOrGroup" } } do |f|%>
        <div class="individual-search mb-3 row g-3" style="display: none;">
            <div class="col-2">
                <label for="label_filter_student-name" class="visually-hidden">Name</label>
                <input type="text" readonly class="form-control-plaintext text-end" id="label_filter_student-name" value="Name :">
            </div>
            <div class="col-3">
                <label for="form_date_filter_student-name" class="visually-hidden"></label>
                <% user = User.where(status: "active").where.not(role: 1).index_by(&:id) %>
                <%= f.select "student-name", user.collect {|k, v| ["#{v["firstname"]} #{v["lastname"]}", k]}, { prompt: "-- Please select student --" }, class: "form-select w-100" %>
            </div>
            <div class="col-1">
                <button type="submit" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                    </svg>
                </button>
            </div>

            <div class="col-6">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addExamDateModal" data-action="click->dashboard#openAddExamDate">Add exam date</button>
            </div>
        </div>

        <div class="group-search mb-3 row">
            <div class="col-2 form-floating">
                <%= f.select "class", study_class(), { include_blank: "-- Select class --", selected: "#{session["current_user"]["study_class"]}" }, class: "form-select w-100", id: "select_class" %>
                <label class="ms-2" for="select_class">Class: </label>
            </div>
            <div class="col-3 form-floating">
                <%= f.select "musical", MusicalInstrument.all.pluck(:musical_instruments_en, :id), { include_blank: "-- Select musical group --" }, class: "form-select w-100", id: "select_musical_instrument" %>
                <label class="ms-2" for="select_musical_instrument">Music instrument: </label>
            </div>
            <div class="col-3 form-floating">
                <%= f.select "exam_date", exam_date(), { include_blank: "-- Select going exam date --" }, class: "form-select w-75 d-inline", id: "select_exam_date" %>
                <label class="ms-2" for="select_exam_date">Going exam date: </label>
                <button type="submit" class="btn btn-primary float-end mt-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                    </svg>
                </button>
            </div>
        </div>
    <% end %>
</div>

pd_music/app/views/dashboard/_filter_graph.html.erb
<div class="mb-3">
    <div class="btn-group" role="group" aria-label="filter-date">
        <input type="radio" class="btn-check" name="btnradio" id="today-filter" autocomplete="off" data-action="change->dashboard#selectDateRange" data-dashboard-date-param="week" data-dashboard-url-param="<%= dashboard_filter_path %>" checked>
        <label class="btn btn-outline-primary" for="today-filter">Week</label>

        <input type="radio" class="btn-check" name="btnradio" id="week-filter" autocomplete="off" data-action="change->dashboard#selectDateRange" data-dashboard-date-param="month" data-dashboard-url-param="<%= dashboard_filter_path %>">
        <label class="btn btn-outline-primary" for="week-filter">Month</label>

        <div class="btn-group dropright">
            <input type="radio" class="btn-check" name="btnradio" id="date-range-filter" autocomplete="off" data-action="change->dashboard#showDateRange" >
            <label class="btn btn-outline-primary rounded-end" for="date-range-filter">Date Rage</label>

            <div class="dropdown-menu dropdown-date-range row px-2 py-2" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(85px, 25px, 0px);">
                <%= form_for :form_date_filter, url: dashboard_filter_path(format: :json), method: :POST, html: { data: { "action": "submit->dashboard#filterDateRange" } } do |f|%>
                    <div class="mb-3">
                        <label for="date-from" class="form-label">Date form :</label>
                        <%= f.date_field :date_from, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: "form-control", id: "date-from" %>
                    </div>
                    <div class="mb-3">
                        <label for="date-to" class="form-label">To: </label>
                        <%= f.date_field :date_to, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: "form-control", id: "date-to" %>
                    </div>
                    <div class="mb-2 text-center">
                        <%= f.submit "Search", class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>    
</div>

pd_music/app/views/dashboard/_graph.html.erb
<%= line_chart graph, colors: color, max: 10, height: "258px", legend: "top", id: "chart-frequency" %>

pd_music/app/views/dashboard/_table_comment_admin.html.erb
<%= content_tag :table, class: "table table-striped dashboard-hw-table", id: "table-behaviour-comment-list-admin", width: "100%" do %>
    <thead>
        <tr>
            <th class="text-start column-0">Student name</th>
            <th class="text-center column-1">Negative</th>
            <th class="text-start column-2">Status</th>
            <th class="text-start column-3">Latest comment</th>
            <th class="text-center column-4">Action</th>
        </tr>
    </thead>
    <tbody>
        <% behaviour.each do |k, v| %>
        <tr>
            <td class="text-start truncate" data-bs-toggle="tooltip" data-bs-html="true" title="<span class='tooltip-text'><%= k %></span>">
                <%= k %>
            </td>
            <td class="text-center"><%= v["negative_times"] %></td>
            <td class="text-start" id="behaviour-status-<%= v["id"] %>"><%= v["status"] %></td>
            <td class="text-start"><%= v["latest_comment"].strftime("%d/%m/%Y") %></td>
            <td class="text-center" id="action-<%= v["id"] %>">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-text-fill icon" viewBox="0 0 16 16" data-bs-target="#showCommentClassRoom" data-action="click->dashboard#showToolsTip click->dashboard#expandComment click->dashboard#viewUser" data-dashboard-url-param="<%= dashboard_view_user_comment_path() %>" data-dashboard-id-param="<%= v["id"] %>" data-bs-toggle="modal" data-bs-dismiss="modal">
                    <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0M9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1M4.5 9a.5.5 0 0 1 0-1h7a.5.5 0 0 1 0 1zM4 10.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m.5 2.5a.5.5 0 0 1 0-1h4a.5.5 0 0 1 0 1z"/>
                </svg>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square icon" viewBox="0 0 16 16" data-action="click->dashboard#editStatus" data-dashboard-id-param="<%= v["id"] %>">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                </svg>
            </td>
        </tr>
        <% end %>
    </tbody>
<% end %>

pd_music/app/views/dashboard/index.html.erb
<% is_user_logged_in? %>

<% if session["current_user"]["first_login"] == 0 %>
    <div id="div-profile-pic-upload-dialog">
        <%= render partial: "upload_picture_dialog" %>
    </div>
<% end %>
<div class="h-100" data-controller="dashboard">
    <%# <h5 class="title-menu mb-3">Dashboard</h5> %>
    <ul class="nav nav-tabs nav-tabs-dashboard z-index-99">
        <li class="nav-item text-center">
            <a class="nav-link dashboard-tab active" id="dashboard-tab-all" aria-current="page" data-action="click->dashboard#selectTab" data-dashboard-tab-param="all" data-dashboard-id-param="" data-dashboard-url-param="<%= dashboard_change_tab_path() %>">All</a>
        </li>
        <% @category.each do |k, v| %>
            <li class="nav-item text-center">
                <a class="nav-link dashboard-tab" id="dashboard-tab-<%= v["name_en"] %>" data-action="click->dashboard#selectTab" data-dashboard-tab-param="<%= v["name_en"] %>" data-dashboard-id-param="<%= v["id"] %>" data-dashboard-url-param="<%= dashboard_change_tab_path() %>"><%= v["name_en"].capitalize %></a>
            </li>
        <% end %>
    </ul>

    <% if can_view_menu?([3]) %>
        <div class="div-filter-content border w-100 z-index-99">
            <%= render partial: "filter_for_teacher" %>
        </div>
        <div class="filter-icon-dashboard text-center position-absolute start-50 z-index-99">
            <button class="btn btn-primary rounded-bottom" style="border-top-left-radius: 0px !important; border-top-right-radius: 0px !important;" data-controller="dashboard" data-action="click->dashboard#clickFilter">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-funnel-fill" viewBox="0 0 16 16">
                    <path d="M1.5 1.5A.5.5 0 0 1 2 1h12a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.128.334L10 8.692V13.5a.5.5 0 0 1-.342.474l-3 1A.5.5 0 0 1 6 14.5V8.692L1.628 3.834A.5.5 0 0 1 1.5 3.5z"/>
                </svg> Filter
            </button>
        </div>
        <input type="hidden" id="hide-select-state" data-select="group_id" value="" >
        <input type="hidden" id="hide-select-class" value="<%= session["current_user"]["study_class"] %>">
        <input type="hidden" id="hide-select-exam-date" value="">
    <% end %>

    <% if can_view_menu?([5]) %>
        <div class="div-filter-dashboard ms-4 mt-3">
            <h5 class="title-dashboard"><span>Result of </span><span class="title-group-name" id="title-group-name">class : <%= session["current_user"]["study_class"] %></span></h5>
        </div>
    <% end %>

    <% if session["current_user"]["exam_date"].present? %>
        <div class="w-100" id="scroll-container">
            <div id="scroll-text">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-megaphone-fill me-3" viewBox="0 0 16 16">
                    <path d="M13 2.5a1.5 1.5 0 0 1 3 0v11a1.5 1.5 0 0 1-3 0zm-1 .724c-2.067.95-4.539 1.481-7 1.656v6.237a25 25 0 0 1 1.088.085c2.053.204 4.038.668 5.912 1.56zm-8 7.841V4.934c-.68.027-1.399.043-2.008.053A2.02 2.02 0 0 0 0 7v2c0 1.106.896 1.996 1.994 2.009l.496.008a64 64 0 0 1 1.51.048m1.39 1.081q.428.032.85.078l.253 1.69a1 1 0 0 1-.983 1.187h-.548a1 1 0 0 1-.916-.599l-1.314-2.48a66 66 0 0 1 1.692.064q.491.026.966.06"/>
                </svg>  Announcement: You exam date is <%= session["current_user"]["exam_date"].strftime("%d %B %Y") %>
            </div>
        </div>
    <% end %>
    <input type="hidden" id="hide-select-state" data-select="id" value="<%= session["current_user"]["id"] %>">

    <input type="hidden" id="hide-category" value="" />

    <div class="div-dashboard mt-3 mb-5" id="div-dashboard">
        <%= render partial: "summary_box" %>
    </div>
</div>

<div class="modal fade" id="addExamDateModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addExamDateModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addExamDateModalLabel">Add exam date</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <%= form_for :form_add_exam_date, url: dashboard_add_exam_date_path(format: :json), method: :POST do |f| %>
                    <div class="mb-3">
                        <label for="student_name" class="form-label">Student name</label>
                        <%= f.text_field :student_name, value: "", class: "form-control", id: "student_name", disabled: true %>
                        <%= f.hidden_field :student_id, value: "", id: "exam-date_student-id" %>
                    </div>
                    <div class="mb-3">
                        <label for="exam_date" class="form-label">Exam date</label>
                        <%= f.date_field :exam_date, as: :date, value: DateTime.now().strftime("%Y-%m-%d"), class: "form-control" , id: "exam_date" %>
                    </div>

                    <div class="mb-3 text-center">
                        <%= f.submit "Add", class: "btn btn-primary", id: "btn-add-tag" %>
                        <button type="button" class="btn btn-outline-primary" id="btn-close-add-tag" data-bs-dismiss="modal">Close</button>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>