pd_music/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
  get "login", to: "login#index"
  post "login/authenicate", to: "login#authenicate"
  get "login/signup", to: "login#signup"
  post "login/register", to: "login#register"
  get "login/logout", to: "login#logout"
  get "login/forgot_password", to: "login#forgot_password"
  post "login/reset_password", to: "login#reset_password"
  get "login/reset", to: "login#new_password"
  post "login/change_password", to: "login#change_password"

  post "dashboard/filter", to: "dashboard#filter_report"
  get "dashboard/datatable", to: "dashboard#dashboard_datatable"
  post "dashboard/change_tab", to: "dashboard#change_tab"
  post "dashboard/comment", to: "dashboard#add_comment"
  post "dashboard/view_user_comment", to: "dashboard#view_user_comment"
  post "dashboard/update_status", to: "dashboard#update_status"
  post "dashboard/add_exam_date", to: "dashboard#add_exam_date"

  get "report", to: "report#index"
  get "report/filter_user_or_subject", to: "report#filter_user_or_subject"
  get "report/filter_category", to: "report#filter_category"
  get "report/filter_homework", to: "report#filter_homework"
  get "report/filter_graph", to: "report#filter_graph"

  resources :homework
  post "homework/do/create_question", to: "homework#create_question"
  get "homework/do/detail_datatable", to: "homework#detail_datatable"
  get "homework/do/detail_score_datatable", to: "homework#get_detail_score"
  get "homework/do/datatable", to: "homework#datatable"
  get "homework/do/homework", to: "homework#do_homework"
  post "homework/do/set_audio", to: "homework#set_audio"
  post "homework/do/update_status", to: "homework#update_status"
  get "homework/do/reveal_answer", to: "homework#get_reveal_answer"
  post "homework/do/next_question", to: "homework#get_next_question"
  get "homework/do/review_homework", to: "homework#review_homework"
  post "homework/do/give_homework_score", to: "homework#give_score"
  post "homework/do/reject_homework", to: "homework#reject_homework"
  get "homework/subject/list", to: "homework#subject_list" 
  post "homework/create_tag", to: "homework#create_tag"
  get "homework/show/get_improvement_detail", to: "homework#get_improvement"
  post "homework/add_improvement", to: "homework#add_improvement"
  get "homework/show/homework_table", to: "homework#show_homework_table"
  delete "homework/show/delete_homework", to: "homework#delete_homework"
  post "homework/add_type", to: "homework#add_homework_type"
  post "homework/answer_format", to: "homework#select_answer_format"
  post "homework/add/question", to: "homework#add_questions"
  post "homework/add_choice", to: "homework#add_choices"
  get "homework/subject/get_user", to: "homework#get_user_homework_mapping"
  post "homework/add_user", to: "homework#add_user_to_homework"

  resources :participation
  post "participation/filter_report", to: "participation#filter"
  post "participation/add_subject", to: "participation#add_subject"
  post "participation/add_event", to: "participation#add_event"
  post "participation/add_user", to: "participation#add_user_to_subject"
  get "participation/subject/get_user", to: "participation#get_participate_of_user"
  post "participation/filter_subject", to: "participation#search_subject"

  resources :user
  get "user/datatable", to: "user#datatable"
  post "user/upload_profile_picture", to: "user#upload_profile_picture"
  post "user/list/approved", to: "user#approve_user"

  get "settings/notification", to: "notification#index"
  post "settings/save_notification", to: "notification#save_notification_setting"
  post "notification/filter", to: "notification#filter"
  post "notification/update", to: "notification#update_noti"
  
  get "settings/permission", to: "permission#index"
  post "settings/update_permission", to: "permission#update_permission"

  get "food", to: "food#index"
  post "food/set_order_rule", to: "food#setting_order"
  post "food/export_order", to: "food#export_order"
  get "food/filter_date", to: "food#filter_date"
  post "food/add_coupon", to: "food#add_coupon"
  get "food/restaurants", to: "food#restaurant"
  delete "food/restaurants", to: "food#destroy"
  post "food/restaurants/update_status", to: "food#update_restaurant_status"
  post "food/create", to: "food#create"
  get "food/menu", to: "food#menu_list"
  get "food/menu/datatable", to: "food#menu_datatable"
  post "food/menu/create", to: "food#create_menu"
  post "food/menu/option_create", to: "food#create_option"
  get "food/menu/get_option", to: "food#get_option"
  get "food/menu/get_menu", to: "food#get_menu"
  post "food/menu/update_status", to: "food#update_status"
  get "food/order", to: "food#order"
  delete "food/order", to: "food#destroy_order"
  get "food/order/get_menu", to: "food#get_menu_order"
  post "food/order/confirm", to: "food#confirm_order"
  get "food/order/change_date", to: "food#change_date"

  get "contact_us", to: "contact_us#index"

  get "activity_log", to: "activity_log#index"
  get "activity_log/datatable", to: "activity_log#datatable"

  get "category/show/datatable", to: "category#datatable"
  resources :category

  get "homework_type/show/datatable", to: "homework_type#datatable"
  resources :homework_type
end

pd_music/app/views/layouts/_flash_alert.html.erb
<div class="toast-container position-absolute top-0 end-0 p-3">
    <% flash.each do |key, value| %>
        <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-controller="flash-alert" data-flash-alert-target="toast">
            <div class="toast-header">
                <% case key %>
                <% when "success" %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle-fill alert-icon-<%= key %>" viewBox="0 0 16 16">
                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                    </svg>
                <% when "error" %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-circle-fill alert-icon-<%= key %>" viewBox="0 0 16 16">
                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4m.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2"/>
                    </svg>
                <% when "info" %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle-fill alert-icon-<%= key %>" viewBox="0 0 16 16">
                        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2"/>
                    </svg>
                <% end %>
                <%# <img src="..." class="rounded me-2" alt="..."> %>
                <strong class="me-auto text-<%= key %> ms-2"><%= key.capitalize %></strong>
                <%# <small class="text-muted">just now</small> %>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body toast-body-<%= key %>">
                <%= value %>
            </div>
        </div>
    <% end %>
</div>

pd_music/app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-light bg-light" data-controller="layout">
    <div class="w-100">
        <button class="hamburger-icon text-center rounded-3 ms-4 me-3 d-inline" data-action="click->layout#miniSideMenu">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
            </svg>
        </button>
        <%= link_to root_path(), class: "navbar-brand" do %>
            <%# <img src="/pictures/logo-removebg.png" alt="" width="40" height="30" class="d-inline-block align-text-top"> %>
            <span class="nav-logo">PD Music school</span>
        <% end %>
        <div class="btn-group float-end me-3">
            <div class="dropdown mx-3" style="align-content: center;">
                <% noti = Notification.where(user_id: session["current_user"]["id"]) %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill notification-icon dropdown-toggle" viewBox="0 0 16 16" id="dropdownNotification" data-bs-toggle="dropdown" aria-expanded="false">
                    <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2m.995-14.901a1 1 0 1 0-1.99 0A5 5 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901"/>
                </svg>
                <% count_noti = noti.count %>
                <% if count_noti > 0 %>
                <span class="position-absolute translate-middle badge rounded-pill bg-danger" style="top: 10px; left: 20px; min-width: 25px;">
                    <% alert_count = count_noti >= 100 ? "99+" : count_noti %>
                    <%= alert_count %>
                    <span class="visually-hidden">unread messages</span>
                </span>
                <% end %>

                <div class="dropdown-menu dropdown-menu-lg-end py-0 my-0" aria-labelledby="dropdownNotification" style="width: 500px !important;">
                    <div class="row ms-2">
                        <div class="col-5 border-end py-2">
                            <div class="mb-2"><span>Filter :</span></div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="RadioNotification" id="Notification0" value="" data-action="change->layout#filterNoti" data-layout-url-param="<%= notification_filter_path() %>" checked>
                                <label class="form-check-label" for="Notification0">
                                    All
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="RadioNotification" id="Notification1" value="new_assign" data-action="change->layout#filterNoti" data-layout-url-param="<%= notification_filter_path() %>">
                                <label class="form-check-label" for="Notification1">
                                    New assign homework
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="RadioNotification" id="Notification2" value="overdue" data-action="change->layout#filterNoti" data-layout-url-param="<%= notification_filter_path() %>">
                                <label class="form-check-label" for="Notification2">
                                    Going overdue
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="RadioNotification" id="Notification3" value="behaviour" data-action="change->layout#filterNoti" data-layout-url-param="<%= notification_filter_path() %>">
                                <label class="form-check-label" for="Notification3">
                                    Comment behaviour
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="RadioNotification" id="Notification4" value="homework" data-action="change->layout#filterNoti" data-layout-url-param="<%= notification_filter_path() %>">
                                <label class="form-check-label" for="Notification4">
                                    Comment homework
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="RadioNotification" id="Notification5" value="change_status" data-action="change->layout#filterNoti" data-layout-url-param="<%= notification_filter_path() %>">
                                <label class="form-check-label" for="Notification5">
                                    Send/Reject/Checked homework
                                </label>
                            </div>
                        </div>
                        <div class="col-7 ps-0 div-noti-list">
                            <%= render partial: "layouts/notification", locals: {notification: noti} %>
                        </div>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-logout dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                <%= image_tag(session["current_user"]["profile_pic"], class: "rounded-circle border me-1", width: "30px", height: "30px") %>
                <%= session["current_user"]["username"] %>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
                <li class="dropdown-li"><%= button_to "Change profile", edit_user_path(id: session["current_user"]["id"]), method: :get, class: "dropdown-item" %></li>
                <li class="dropdown-li"><%= button_to "Log out", login_logout_path(), method: :get, class: "dropdown-item" %></li>
                <%# <li><button class="dropdown-item" type="button">Action</button></li>
                <li><button class="dropdown-item" type="button">Another action</button></li>
                <li><button class="dropdown-item" type="button">Something else here</button></li> %>
            </ul>
        </div>
    </div>
</nav>

pd_music/app/views/layouts/_notification.html.erb
<% notification.each_with_index do |n, index| %>
    <% status = n.status == 0 ? "unread" : "" %>
    <div class="div-noti <%= status %> pt-3" data-controller="layout" data-action="click->layout#updateNoti" data-layout-url-param="<%= notification_update_path(id: n.id, type: n.notification_type) %>">
        <div class="subject-noti ps-2"><p class="m-0"><%= n.subject %></p></div>
        <div class="msg-noti <%= status %> ps-2"><p class="m-0"><%= n.message %></p></div>
        <div class="text-end datetime-noti pe-2"><p class="mb-3"><%= n.updated_at.strftime("%H:%M:%S %d/%m/%Y") %></p></div>
    </div>
    <% break if index == 4 %>
<% end %>

pd_music/app/views/layouts/_session_timeout_dialog.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" id="session-timeout-btn" data-bs-toggle="modal" data-bs-target="#sessionTimeout" style="display: none;" data-controller="session">
  Session timeout
</button>

<!-- Modal -->
<div class="modal fade" id="sessionTimeout" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="sessionTimeoutLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="sessionTimeoutLabel">Session Timeout</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <span>Your session was expired. Please try to login again.</span>
        <p>Website to force logout in <span id="countdown-logout">10</span> second</p>
      </div>
      <div class="modal-footer">
        <%= link_to "OK", login_path(), class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

pd_music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pd music</title>
    <link rel="icon" href="<%= APP_CONFIG[:application_path] %>/pictures/logo-removebg.png" type="image/icon type">
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Athiti:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>

  <body>
    <% unless session["current_user"].blank? %>
      <%= render partial: "layouts/nav_bar" %>
    <% end %>

    <% unless params[:controller] == "login" %>
      <div class="div-side-menu pt-3 position-absolute">
        <%= render partial: "layouts/nav_side_menu" %>
      </div>
      <%= render partial: "layouts/session_timeout_dialog" %>
    <% end %>

    <%= render partial: "layouts/flash_alert" %>

    <div class="div-body">
      <%= yield %>
    </div>
    <%= hidden_field_tag :application_path, "#{APP_CONFIG[:application_path]}", id: "application-path" %>
  </body>
</html>