pd_music/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
  get "login", to: "login#index"
  post "login/authenicate", to: "login#authenicate"
  get "login/signup", to: "login#signup"
  post "login/register", to: "login#register"
  get "login/logout", to: "login#logout"
  get "login/forgot_password", to: "login#forgot_password"
  post "login/reset_password", to: "login#reset_password"
  get "login/reset", to: "login#new_password"
  post "login/change_password", to: "login#change_password"

  post "dashboard/filter", to: "dashboard#filter_report"
  get "dashboard/datatable", to: "dashboard#dashboard_datatable"
  post "dashboard/change_tab", to: "dashboard#change_tab"
  post "dashboard/comment", to: "dashboard#add_comment"
  post "dashboard/view_user_comment", to: "dashboard#view_user_comment"
  post "dashboard/update_status", to: "dashboard#update_status"
  post "dashboard/add_exam_date", to: "dashboard#add_exam_date"

  get "report", to: "report#index"
  get "report/filter_user_or_subject", to: "report#filter_user_or_subject"
  get "report/filter_category", to: "report#filter_category"
  get "report/filter_homework", to: "report#filter_homework"
  get "report/filter_graph", to: "report#filter_graph"

  resources :homework
  post "homework/do/create_question", to: "homework#create_question"
  get "homework/do/detail_datatable", to: "homework#detail_datatable"
  get "homework/do/detail_score_datatable", to: "homework#get_detail_score"
  get "homework/do/datatable", to: "homework#datatable"
  get "homework/do/homework", to: "homework#do_homework"
  post "homework/do/set_audio", to: "homework#set_audio"
  post "homework/do/update_status", to: "homework#update_status"
  get "homework/do/reveal_answer", to: "homework#get_reveal_answer"
  post "homework/do/next_question", to: "homework#get_next_question"
  get "homework/do/review_homework", to: "homework#review_homework"
  post "homework/do/give_homework_score", to: "homework#give_score"
  post "homework/do/reject_homework", to: "homework#reject_homework"
  get "homework/subject/list", to: "homework#subject_list" 
  post "homework/create_tag", to: "homework#create_tag"
  get "homework/show/get_improvement_detail", to: "homework#get_improvement"
  post "homework/add_improvement", to: "homework#add_improvement"
  get "homework/show/homework_table", to: "homework#show_homework_table"
  delete "homework/show/delete_homework", to: "homework#delete_homework"
  post "homework/add_type", to: "homework#add_homework_type"
  post "homework/answer_format", to: "homework#select_answer_format"
  post "homework/add/question", to: "homework#add_questions"
  post "homework/add_choice", to: "homework#add_choices"
  get "homework/subject/get_user", to: "homework#get_user_homework_mapping"
  post "homework/add_user", to: "homework#add_user_to_homework"

  resources :participation
  post "participation/filter_report", to: "participation#filter"
  post "participation/add_subject", to: "participation#add_subject"
  post "participation/add_event", to: "participation#add_event"
  post "participation/add_user", to: "participation#add_user_to_subject"
  get "participation/subject/get_user", to: "participation#get_participate_of_user"
  post "participation/filter_subject", to: "participation#search_subject"

  resources :user
  get "user/datatable", to: "user#datatable"
  post "user/upload_profile_picture", to: "user#upload_profile_picture"
  post "user/list/approved", to: "user#approve_user"

  get "settings/notification", to: "notification#index"
  post "settings/save_notification", to: "notification#save_notification_setting"
  post "notification/filter", to: "notification#filter"
  post "notification/update", to: "notification#update_noti"
  
  get "settings/permission", to: "permission#index"
  post "settings/update_permission", to: "permission#update_permission"

  get "food", to: "food#index"
  post "food/set_order_rule", to: "food#setting_order"
  post "food/export_order", to: "food#export_order"
  get "food/filter_date", to: "food#filter_date"
  post "food/add_coupon", to: "food#add_coupon"
  get "food/restaurants", to: "food#restaurant"
  delete "food/restaurants", to: "food#destroy"
  post "food/restaurants/update_status", to: "food#update_restaurant_status"
  post "food/create", to: "food#create"
  get "food/menu", to: "food#menu_list"
  get "food/menu/datatable", to: "food#menu_datatable"
  post "food/menu/create", to: "food#create_menu"
  post "food/menu/option_create", to: "food#create_option"
  get "food/menu/get_option", to: "food#get_option"
  get "food/menu/get_menu", to: "food#get_menu"
  post "food/menu/update_status", to: "food#update_status"
  get "food/order", to: "food#order"
  delete "food/order", to: "food#destroy_order"
  get "food/order/get_menu", to: "food#get_menu_order"
  post "food/order/confirm", to: "food#confirm_order"
  get "food/order/change_date", to: "food#change_date"

  get "contact_us", to: "contact_us#index"

  get "activity_log", to: "activity_log#index"
  get "activity_log/datatable", to: "activity_log#datatable"

  get "category/show/datatable", to: "category#datatable"
  resources :category

  get "homework_type/show/datatable", to: "homework_type#datatable"
  resources :homework_type
end

pd_music/app/models/homework_type.rb
class HomeworkType < ApplicationRecord
end

pd_music/app/controllers/homework_controller.rb
class HomeworkController < ApplicationController
    include HomeworkHelper

    def index
        unless can_view_menu?([33])
            flash["error"] = "You don't have permission to view homework"
            return redirect_to path_to_root
        end
        if session["current_user"]["role"] == 3
            @homework = HomeworkUserMapping.joins("left join homeworks on homeworks.id = homework_user_mappings.homework_id")
            @homework = @homework.where(user_id: session["current_user"]["id"])
            @homework = @homework.where("homeworks.status = ?", "active")
            @homework = @homework.where("homeworks.estimate_date < ?", DateTime.now().strftime("%Y-%m-%d %H:%M:%S")).limit(1)
        else
            @subject = Subject.where(status: "active", subject_type: "homework")
            @homework_list = Homework.where(status: "active")
        end
    end

    def detail_datatable
        respond_to do |format|
            format.html
            format.json { render json: DetailHomeworkDatatable.new(params, view_context: view_context) }
        end
    end

    def datatable
        respond_to do |format|
            format.html
            format.json { render json: HomeworkDatatable.new(params, view_context: view_context) }
        end
    end

    def update_status
        begin
            id = params["id"].split(",")
            homework = HomeworkUserMapping.where(id: id)
            homework.update_all(status: params["status"])
            save_activity("Homework", "Success", "Update homework status to #{params["status"]}")
            # state = "success"
            # message = "Update homework status successfully"
            render(
                partial: "homework/table_detail_homework_list",
                formats: [:html, :js, :json, :url_encoded_form]
            )

        rescue => e
            save_activity("Homework", "Fail", "Fail to update homework status")
            respond_to do |format|
                format.json { render json: {state: "error", message: "Something was wrong. Please contact admin"} }
            end
        end
        
    end

    def get_detail_score
        user = User.select("users.id, users.firstname, users.lastname, users.profile_pic, homeworks.id as homework_id, homeworks.task_name, homeworks.estimate_date, homeworks.full_score, homework_user_mappings.id as homework_mapping_id, homework_user_mappings.score, homework_user_mappings.status, homework_user_mappings.send_date, subjects.subject_name")
        user = user.joins("right join homework_user_mappings on homework_user_mappings.user_id = users.id")
        user = user.joins("left join homeworks on homeworks.id = homework_user_mappings.homework_id")
        user = user.joins("left join subjects on subjects.id = homeworks.subject_id")
        # homework = homework.order("homeworks.subject_id, homeworks.id")

        homework = Homework.where(status: "active")
        data = Hash.new
        score = Hash.new
        user.each do |u|
            data["#{u.firstname.capitalize} #{u.lastname.capitalize}"] ||= {}
            begin
                if (u.send_date <= u.estimate_date)
                    status = "sent"
                    status = "need_review" if u.status == "send"
                else
                    status = "open"
                    status = "need_review" if u.status == "send"
                    status = "late" if u.status == "checked"
                end
            rescue => e
                status = "open"
            end
            data["#{u.firstname.capitalize} #{u.lastname.capitalize}"][u.task_name] = [u.score.to_i, status, u.id, u.homework_id, u.homework_mapping_id]
            data["#{u.firstname.capitalize} #{u.lastname.capitalize}"]["profile_pic"] = u.profile_pic
            score[u.task_name] ||= {}
            score[u.task_name]["score"] ||= 0
            score[u.task_name]["score"] += u.score.to_i
            score[u.task_name]["number"] ||= 0
            score[u.task_name]["number"] += 1
        end

        render(
            partial: "homework/score_detail",
            formats: [:html, :js, :json, :url_encoded_form],
            locals: {data: data, score: score, homework: homework}
        )
    end

    def do_homework
        @h_homework = Hash.new
        homework = Question.select("questions.*, homeworks.task_name, homeworks.status, homeworks.estimate_date, homeworks.category_id, homeworks.full_score, homeworks.subject_id, homeworks.is_default, homeworks.priority ,homeworks.homework_type_id")
        homework = homework.where(homework_id: params["id"])
        homework = homework.joins("left join homeworks on homeworks.id = questions.homework_id")
        homework = homework.order(question_no: :ASC)

        answer = Answer.where(homework_id: params["id"], user_id: session["current_user"]["id"]).order(question_no: :ASC)
        answer_id = nil
        answers = []
        if answer.blank?
            @h_homework["current_score"] = 0
            @h_homework["current_progress"] = 0
            @h_homework["current_reveal"] = 0
            @h_homework["current_question"] = 1
        else
            # answer = answer.maximum(:question_no)
            has_reject = false
            answer.each_with_index do |ans, index|
                @h_homework["current_score"] ||= 0 #ans.current_score
                @h_homework["current_score"] += ans.current_score
                @h_homework["current_reveal"] = ans.current_reveal_time
                @h_homework["current_progress"] = ans.current_progress
                if ans.current_progress.blank? && !has_reject
                    has_reject = true
                    @h_homework["current_question"] = ans.question_no
                    answer_id = ans.id
                    answers = ans.answer.blank? ? [] : ans.answer.split(",")
                elsif ans.current_progress.present?
                    @h_homework["current_question"] = ans.question_no+1
                end
            end
        end
        
        hash_question = Hash.new
        homework.each do |hw|
            @h_homework["homework_id"] = params["id"]
            @h_homework["task_name"] = hw.task_name
            @h_homework["full_score"] = hw.full_score
            @h_homework["question_length"] ||= []
            @h_homework["question_length"] << hw.question_no
            @h_homework["questions"] ||= []
            hash_question["no_#{hw.question_no}"] ||= {}
            hash_question["no_#{hw.question_no}"]["id"] = hw.id
            hash_question["no_#{hw.question_no}"]["question_no"] = hw.question_no
            hash_question["no_#{hw.question_no}"]["score"] = hw.score
            hash_question["no_#{hw.question_no}"]["question"] = hw.question
            hash_question["no_#{hw.question_no}"]["question_media"] = hw.question_media
            hash_question["no_#{hw.question_no}"]["answer_id"] = answer_id
            hash_question["no_#{hw.question_no}"]["answer"] = answers
            hash_question["no_#{hw.question_no}"]["image_thumbnail"] = hw.image_thumbnail
            # p url_for(hw.question_media)
            hash_question["no_#{hw.question_no}"]["answer_format"] = hw.answer_format
            hash_question["no_#{hw.question_no}"]["chords"] = hw.chords
            hash_question["no_#{hw.question_no}"]["choice"] ||= []
            answer = hw.answer.attached? ? hw.answer : hw.answer_text
            hash_question["no_#{hw.question_no}"]["choice"] << [hw.choice_no, answer, hw.answer_image_thumbnail]
            hash_question["no_#{hw.question_no}"]["option"] = hw.option
            hash_question["no_#{hw.question_no}"]["reveal"] = hw.reveal
            @h_homework["questions"] << hash_question
        end
        @h_homework["question_length"].uniq!
    end

    def set_audio
        if params["answer_id"].blank?
            answer = Answer.insert_audio(params)
        else
            answer = Answer.update_audio(params)
        end
        # $record_audio = Hash.new
        # $record_audio["audio_#{params["times"]}"] = params["record_audio"]
        # file = params["record_audio"]
        respond_to do |format|
            format.json { render json: {times: params["times"], answer_id: answer.id} }
        end
    end

    def get_reveal_answer
        question = Question.find(params["id"])
        reveal_answer = question.reveal.attached? ? url_for(question.reveal) : ""

        respond_to do |format|
            format.json { render json: {correct_answer: question.correct_answer, answer_media: reveal_answer, reveal_image_size: question.answer_image_thumbnail} }
        end
    end

    def get_next_question
        @h_homework = Hash.new
        begin

            if params["form_answer"]["answer_id"].blank?
                answer = Answer.insert_answer(session, params)
            else
                answer = Answer.update_answer(session, params)
            end

            if (params["question_no"].to_i)-1 == params["questions"].length
                homework_mapping = HomeworkUserMapping.where(homework_id: params["id"], user_id: session["current_user"]["id"])
                check_questions = Question.where(homework_id: params["id"]).pluck(:answer_format)
                status = check_questions.include?(3) ? "send" : "checked"
                homework_mapping.update(score: params["score"], status: status, send_date: DateTime.now())
                save_activity("Do Homework", "Success", "Do homework successfully")
                flash["success"] = "Do homework successfully, your score: #{params["score"]}"

                recheck_message = check_questions.include?(3) ? " Please review and give the score." : ""
                ### Send notification
                if can_view_menu?([15])
                    homework_info = Homework.select("subjects.subject_name, subjects.created_by, homeworks.task_name").find(params["id"]).joins("left join subjects on subjects.id = homeworks.subject_id")

pd_music/app/helpers/homework_helper.rb
module HomeworkHelper
    def get_status
        return [["Open", "open"], ["Send", "send"], ["Reject", "reject"], ["Checked", "checked"]]
    end

    def deadline_date
        [["1 Day", "1"], ["2 Day", "2"], ["3 Day", "3"], ["4 Day", "4"], ["5 Day", "5"], ["6 Day", "6"], ["1 Week", "7"], ["2 Week", "14"], ["3 Week", "21"], ["1 Month", "30"]]
    end
end

pd_music/app/views/homework/_add_homework_type.html.erb
<div class="modal fade" id="addHomeworkTypeModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addHomeworkTypeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addHomeworkTypeModalLabel">Add homework type</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <%= form_for :form_homework_type, url: homework_add_type_path(format: :json, subject_id: id, subject: subject, category: category_id), method: :POST, html: { data: { action: "submit->homework#addHomeworktypeSuccess" } }  do |f| %>
                    <div class="mb-3">
                        <label for="homework_type" class="form-label">Homework type</label>
                        <%= f.text_field :homework_type, value: params["type"], class: "form-control", id: "homework_type", placeholder: "Day" %>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label">Description</label>
                        <%= f.text_area :description, value: params["description"], class: "form-control", id: "description", rows: "2" %>
                    </div>

                    <div class="mb-3 text-center">
                        <%= f.submit "Add", class: "btn btn-primary", id: "btn-add-hw-type" %>
                        <button type="button" class="btn btn-outline-primary" id="btn-close-add-hw-type" data-bs-dismiss="modal">Close</button>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

pd_music/app/views/homework/_show_question.html.erb
<div class="row border rounded-3 w-90 m-auto p-3 mb-3">
    <div class="col-12">
        <label class="form-label head-question-no">Question <%= question[index]["no_#{question_no}"]["question_no"] %> : <%= question[index]["no_#{question_no}"]["question"] %></label>
        
        <% if question[index]["no_#{question_no}"]["question_media"].attached? %>
            <div class="media-questions text-center">
                <% media = url_for(question[index]["no_#{question_no}"]["question_media"]) %>
                <% if question[index]["no_#{question_no}"]["question_media"].content_type.include?("image") %>
                    <% if question[index]["no_#{question_no}"]["image_thumbnail"].blank? %>
                        <% set_size = "" %>
                    <% else %>
                        <% width, height = question[index]["no_#{question_no}"]["image_thumbnail"].split("x") %>
                        <% set_size = "width: #{width}px; height: #{height}px" %>
                    <% end %>
                    <div class="div-image m-auto" id="div-image-<%= question_no %>" style="justify-content: center; overflow: hidden; <%= set_size %>">
                        <img src=<%= url_for(media) %> />
                    </div>
                    
                <% elsif question[index]["no_#{question_no}"]["question_media"].content_type.include?("video") %>
                    <video src=<%= url_for(media) %> autoplay=true controls=true style="width: 500px; height: 250px;"><video>
                <% elsif question[index]["no_#{question_no}"]["question_media"].content_type.include?("audio") %>
                    <div class="div-audio text-center m-auto rounded-3 ms-3 active">
                        <audio src=<%= url_for(media) %> controls=true style="width: 75%"></audio>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

<%= form_for "form_answer", url: homework_do_next_question_path(format: :json, id: @h_homework["homework_id"], question_no:  question[index]["no_#{question_no}"]["question_no"].to_i+1, questions: @h_homework["question_length"]), method: :POST, id: "form_answer", html: { data: { "action": "submit->do-homework#onSubmitAnswer" } } do |f| %>
    <div class="row border rounded-3 w-90 m-auto p-3 mb-5">
        <% disable_reveal = "" %>
        <div class="col-12">
            <% case question[index]["no_#{question_no}"]["answer_format"].to_i %>
            <% when 1 %>
                <%= render partial: "homework/do_homework/answer_chords", locals: {f: f, question_no: question[index]["no_#{question_no}"]["question_no"].to_i, answer: question[index]["no_#{question_no}"]["chords"], user_answer: question[index]["no_#{question_no}"]["answer"]} %>
            <% when 2 %>
                <%= render partial: "homework/do_homework/answer_choice", locals: {f: f, question_no: question[index]["no_#{question_no}"]["question_no"].to_i, answer: question[index]["no_#{question_no}"]["choice"], user_answer: question[index]["no_#{question_no}"]["answer"]} %>
            <% when 3 %>
                <% disable_reveal = "disabled" %>
                <%= render partial: "homework/do_homework/answer_upload_file", locals: {f: f, question_no: question[index]["no_#{question_no}"]["question_no"].to_i, option: question[index]["no_#{question_no}"]["option"]} %>
            <% end %>
        </div>
        <input type="hidden" id="have-revral-answer" value="0">
        <%= f.hidden_field :answer_id, value: question[index]["no_#{question_no}"]["answer_id"], id: "answer-id" %>
        <%= f.hidden_field :your_answer, value: question[index]["no_#{question_no}"]["answer"], id: "your-answer" %>
        <%= f.hidden_field :your_score, value: 0, id: "your-score", "data-score": question[index]["no_#{question_no}"]["score"].to_i %>
        <%= f.submit "Submit", class: "btn btn-primary d-none", id: "send-answer" %>
    </div>

    <div class="w-90 text-center m-auto">
        <button type="button" class="btn btn-outline-primary mx-4" style="width: 125px;" id="btn-reveal-answer" data-action="click->do-homework#revealAnswer" data-do-homework-format-param=<%= question[index]["no_#{question_no}"]["answer_format"] %> data-do-homework-url-param=<%= homework_do_reveal_answer_path(id: question[index]["no_#{question_no}"]["id"], answer_format: question[index]["no_#{question_no}"]["answer_format"].to_i) %> <%= disable_reveal %>>Reveal answer</button>
        <button type="button" class="btn btn-primary mx-4" style="width: 125px;" data-action="click->do-homework#answer" data-do-homework-format-param=<%= question[index]["no_#{question_no}"]["answer_format"] %> data-do-homework-question-no-param=<%= question[index]["no_#{question_no}"]["question_no"].to_i %> data-do-homework-url-param=<%= homework_do_reveal_answer_path(id: question[index]["no_#{question_no}"]["id"]) %>>Answer</button>
    </div>
<% end %>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary d-none" id="open-answer-result-dialog" data-bs-toggle="modal" data-bs-target="#answerResult"></button>

<!-- Modal -->
<div class="modal fade" id="answerResult" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="answerResultBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="w-100 text-center" id="answer-result-icon">
                    
                </div>
                <div class="w-100" id="answer-result"></div>
            </div>
            <div class="m-3">
                <% button_text = @h_homework["question_length"].length == question[index]["no_#{question_no}"]["question_no"].to_i ? "Submit" : "Next question" %>
                <button type="button" class="btn btn-primary float-end" id="btn-next-question" data-bs-dismiss="modal" data-action="click->do-homework#nextQuestion"><%= button_text %></button>
            </div>
        </div>
    </div>
</div>

pd_music/app/views/homework/_table_homework.html.erb
<table class="table table-hover table-homework-list">
    <thead>
        <tr>
            <th class="column-0 py-3">Homework</th>
            <th class="column-1 py-3">Status</th>
            <th class="column-2 py-3 text-center">Estimated date</th>
            <th class="column-3 py-3 text-center">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @homework.each do |hw| %>
        <tr>
            <td class="py-3"><%= hw.task_name %></td>
            <% case hw.status %>
            <% when "active" %>
                <td class="py-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-unlock-fill lock-icon" viewBox="0 0 16 16">
                        <path d="M11 1a2 2 0 0 0-2 2v4a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5V3a3 3 0 0 1 6 0v4a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2"/>
                    </svg> Active
                </td>
            <% when "inactive" %>
                <td class="py-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                        <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2m3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2"/>
                    </svg> Locked
                </td>
            <% when "deleted" %>
                <td class="py-3">
                    <span>Deleted</span>
                </td>
            <% end %>

            <td class="py-3 text-center"><%= hw.estimate_date.strftime("%d/%m/%Y") %></td>
            <td class="text-center" style="align-content: center;">
                <% if can_view_menu?([37]) %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-person-plus-fill icon" viewBox="0 0 16 16" data-bs-toggle="modal" data-bs-target="#addUserToHomework" data-action="click->homework#openAddUserModal" data-homework-homework-id-param="<%= hw.id %>" data-homework-url-param="<%= homework_subject_get_user_path() %>">
                        <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                        <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"/>
                    </svg>
                <% end %>
                <% if can_view_menu?([35])  %>
                    <%= button_to '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square icon" viewBox="0 0 16 16"><path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/><path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/></svg>'.html_safe, edit_homework_path(id: hw.id), method: :get, class: "btn" %>
                <% end %>
                <% if can_view_menu?([36])  %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16" data-bs-toggle="modal" data-bs-target="#deleteHomeworkModal" data-action="click->homework#setDeleteHomeworkId" data-homework-name-param="<%= hw.task_name %>" data-homework-url-param="<%= homework_show_delete_homework_path(id: hw.id, name: hw.task_name) %>">
                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                    </svg>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<div class="div-add-user-modal">
    <%= render partial: "add_user_to_homework" %>
</div>

<div class="modal fade" id="deleteHomeworkModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="deleteHomeworkLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteHomeworkLabel">Delete</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <span>Are you want to delete <span id="delete-homework-name"></span></span>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger text-white" id="confirm-delete-homework" data-action="click->homework#deleteHomework">Delete</button>
            <button type="button" class="btn btn-outline-primary" id="close-confirm-delete-homework" data-bs-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
</div>